In [61]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv('dataset/used_cars.csv')
df

         brand                            model  ...  clean_title     price
0         Ford  Utility Police Interceptor Base  ...          Yes   $10,300
1      Hyundai                     Palisade SEL  ...          Yes   $38,005
2        Lexus                    RX 350 RX 350  ...          NaN   $54,598
3     INFINITI                 Q50 Hybrid Sport  ...          Yes   $15,500
4         Audi        Q3 45 S line Premium Plus  ...          NaN   $34,999
...        ...                              ...  ...          ...       ...
4004   Bentley             Continental GT Speed  ...          Yes  $349,950
4005      Audi             S4 3.0T Premium Plus  ...          Yes   $53,900
4006   Porsche                           Taycan  ...          NaN   $90,998
4007      Ford                     F-150 Raptor  ...          Yes   $62,999
4008       BMW                     X3 xDrive30i  ...          Yes   $40,000

[4009 rows x 12 columns]

In [63]:
df.replace(['?', 'na', 'nil', ' '], np.nan, inplace=True)
df.isna().sum()

brand             0
model             0
model_year        0
milage            0
fuel_type       170
engine            0
transmission      0
ext_col           0
int_col           0
accident        113
clean_title     596
price             0
dtype: int64

In [64]:
df_cleaned = df.dropna(axis=0)
df_cleaned

              brand                            model  ...  clean_title     price
0              Ford  Utility Police Interceptor Base  ...          Yes   $10,300
1           Hyundai                     Palisade SEL  ...          Yes   $38,005
3          INFINITI                 Q50 Hybrid Sport  ...          Yes   $15,500
6              Audi             S3 2.0T Premium Plus  ...          Yes   $31,000
7               BMW                           740 iL  ...          Yes    $7,300
...             ...                              ...  ...          ...       ...
4003  Mercedes-Benz             E-Class E 300 4MATIC  ...          Yes   $25,900
4004        Bentley             Continental GT Speed  ...          Yes  $349,950
4005           Audi             S4 3.0T Premium Plus  ...          Yes   $53,900
4007           Ford                     F-150 Raptor  ...          Yes   $62,999
4008            BMW                     X3 xDrive30i  ...          Yes   $40,000

[3269 rows x 12 columns]

In [65]:
df_cleaned['milage'] = df_cleaned['milage'].str.replace(',', '').str.replace('mi', '').str.replace('.', '').astype(int)

C:\Users\aqdas\AppData\Local\Temp\ipykernel_5336\1943848012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['milage'] = df_cleaned['milage'].str.replace(',', '').str.replace('mi', '').str.replace('.', '').astype(int)

In [66]:
df_cleaned

              brand                            model  ...  clean_title     price
0              Ford  Utility Police Interceptor Base  ...          Yes   $10,300
1           Hyundai                     Palisade SEL  ...          Yes   $38,005
3          INFINITI                 Q50 Hybrid Sport  ...          Yes   $15,500
6              Audi             S3 2.0T Premium Plus  ...          Yes   $31,000
7               BMW                           740 iL  ...          Yes    $7,300
...             ...                              ...  ...          ...       ...
4003  Mercedes-Benz             E-Class E 300 4MATIC  ...          Yes   $25,900
4004        Bentley             Continental GT Speed  ...          Yes  $349,950
4005           Audi             S4 3.0T Premium Plus  ...          Yes   $53,900
4007           Ford                     F-150 Raptor  ...          Yes   $62,999
4008            BMW                     X3 xDrive30i  ...          Yes   $40,000

[3269 rows x 12 columns]

In [67]:
df_cleaned.milage

0        51000
1        34742
3        88900
6        84000
7       242000
         ...
4003     53705
4004       714
4005     10900
4007     33000
4008     43000
Name: milage, Length: 3269, dtype: int64

In [69]:
df_cleaned['price'] = df_cleaned['price'].str.replace('$', '').str.replace(',', '').astype(int)

C:\Users\aqdas\AppData\Local\Temp\ipykernel_5336\1970450160.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['price'] = df_cleaned['price'].str.replace('$', '').str.replace(',', '').astype(int)

In [70]:
df_cleaned.price

0        10300
1        38005
3        15500
6        31000
7         7300
         ...
4003     25900
4004    349950
4005     53900
4007     62999
4008     40000
Name: price, Length: 3269, dtype: int64

In [83]:
df_cleaned.reset_index(inplace=True)

In [84]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split

In [85]:
X = df_cleaned.iloc[:, 0:-1]
Y = df_cleaned.iloc[:, -1]

In [86]:
Y

0        10300
1        38005
2        15500
3        31000
4         7300
         ...
3264     25900
3265    349950
3266     53900
3267     62999
3268     40000
Name: price, Length: 3269, dtype: int64

In [73]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=42)

In [ ]:
num_features = X.select_dtypes(include=['number'])
num_features

         Price  Mileage  EngineV  Year
0       4200.0      277      2.0  1991
1       7900.0      427      2.9  1999
2      13300.0      358      5.0  2003
3      23000.0      240      4.2  2007
4      18300.0      120      2.0  2011
...        ...      ...      ...   ...
4339   17900.0       35      1.6  2014
4340  125000.0        9      3.0  2014
4341    6500.0        1      3.5  1999
4342    8000.0      194      2.0  1985
4344   13500.0      124      2.0  2013

[4025 rows x 4 columns]

In [ ]:
s_scaler = StandardScaler(with_mean=True)
s_scaler.fit(num_features)

StandardScaler()

In [ ]:
s_scaler.transform(num_features)

array([[-0.5947619 ,  1.09717342, -0.15492109, -2.29726223],
       [-0.45142065,  2.54810497,  0.02743762, -1.10229844],
       [-0.24221991,  1.88067646,  0.45294129, -0.50481654],
       ...,
       [-0.50565788, -1.57254065,  0.1490101 , -1.10229844],
       [-0.44754656,  0.29432462, -0.15492109, -3.19348508],
       [-0.23447173, -0.38277677, -0.15492109,  0.98888821]],
      shape=(4025, 4))

In [ ]:
mm_scaler = MinMaxScaler()
mm_scaler.fit(num_features)

MinMaxScaler()

In [ ]:
mm_scaler.transform(num_features)

array([[0.01202405, 0.28265306, 0.01408592, 0.46808511],
       [0.0243821 , 0.43571429, 0.02314116, 0.63829787],
       [0.04241817, 0.36530612, 0.04427005, 0.72340426],
       ...,
       [0.01970608, 0.00102041, 0.02917799, 0.63829787],
       [0.0247161 , 0.19795918, 0.01408592, 0.34042553],
       [0.04308617, 0.12653061, 0.01408592, 0.93617021]], shape=(4025, 4))

In [ ]:
mm_scaler

MinMaxScaler()

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.read_c